schema_version: '1.0'
generated_at_utc: '2026-02-06T23:14:16.861408+00:00'
source:
  method: extract_json_bootstrap
  input_file: data.json
work_item_type:
  name: Task
  reference_name: Microsoft.VSTS.WorkItemTypes.Task
  description: Tracks work that needs to be done.
  is_disabled: false
  states:
  - name: New
    category: Proposed
    color: b2b2b2
  - name: Active
    category: InProgress
    color: 007acc
  - name: Closed
    category: Completed
    color: '339933'
  - name: Removed
    category: Removed
    color: ffffff
  fields:
  - name: Integration Build
    reference_name: Microsoft.VSTS.Build.IntegrationBuild
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The build in which the bug was fixed
  - name: Activated By
    reference_name: Microsoft.VSTS.Common.ActivatedBy
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Activated Date
    reference_name: Microsoft.VSTS.Common.ActivatedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Activity
    reference_name: Microsoft.VSTS.Common.Activity
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: Type of work involved
  - name: Closed By
    reference_name: Microsoft.VSTS.Common.ClosedBy
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Closed Date
    reference_name: Microsoft.VSTS.Common.ClosedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Priority
    reference_name: Microsoft.VSTS.Common.Priority
    type: null
    read_only: false
    required: false
    default_value: '2'
    help_text: Importance to business
  - name: Stack Rank
    reference_name: Microsoft.VSTS.Common.StackRank
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: Work first on items with lower-valued stack rank. Set in triage.
  - name: State Change Date
    reference_name: Microsoft.VSTS.Common.StateChangeDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Completed Work
    reference_name: Microsoft.VSTS.Scheduling.CompletedWork
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The number of units of work that have been spent on this task
  - name: Finish Date
    reference_name: Microsoft.VSTS.Scheduling.FinishDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The date to finish the task
  - name: Original Estimate
    reference_name: Microsoft.VSTS.Scheduling.OriginalEstimate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: Initial value for Remaining Work - set once, when work begins
  - name: Remaining Work
    reference_name: Microsoft.VSTS.Scheduling.RemainingWork
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: An estimate of the number of units of work remaining to complete this
      task
  - name: Start Date
    reference_name: Microsoft.VSTS.Scheduling.StartDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The date to start the task
  - name: Area ID
    reference_name: System.AreaId
    type: null
    read_only: false
    required: true
    default_value: null
    help_text: null
  - name: Area Level 1
    reference_name: System.AreaLevel1
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 2
    reference_name: System.AreaLevel2
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 3
    reference_name: System.AreaLevel3
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 4
    reference_name: System.AreaLevel4
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 5
    reference_name: System.AreaLevel5
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 6
    reference_name: System.AreaLevel6
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 7
    reference_name: System.AreaLevel7
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Path
    reference_name: System.AreaPath
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The area of the product to which this task contributes
  - name: Assigned To
    reference_name: System.AssignedTo
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The person currently working on this task
  - name: Attached File Count
    reference_name: System.AttachedFileCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Authorized As
    reference_name: System.AuthorizedAs
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Authorized Date
    reference_name: System.AuthorizedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Board Column
    reference_name: System.BoardColumn
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Board Column Done
    reference_name: System.BoardColumnDone
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Board Lane
    reference_name: System.BoardLane
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Changed By
    reference_name: System.ChangedBy
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Changed Date
    reference_name: System.ChangedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Comment Count
    reference_name: System.CommentCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Created By
    reference_name: System.CreatedBy
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Created Date
    reference_name: System.CreatedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Description
    reference_name: System.Description
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: What to do, pointers to resources and inputs, design notes, exit criteria
  - name: External Link Count
    reference_name: System.ExternalLinkCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: History
    reference_name: System.History
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: Discussion thread plus automatic record of changes
  - name: Hyperlink Count
    reference_name: System.HyperLinkCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: ID
    reference_name: System.Id
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration ID
    reference_name: System.IterationId
    type: null
    read_only: false
    required: true
    default_value: null
    help_text: null
  - name: Iteration Level 1
    reference_name: System.IterationLevel1
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 2
    reference_name: System.IterationLevel2
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 3
    reference_name: System.IterationLevel3
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 4
    reference_name: System.IterationLevel4
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 5
    reference_name: System.IterationLevel5
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 6
    reference_name: System.IterationLevel6
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 7
    reference_name: System.IterationLevel7
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Path
    reference_name: System.IterationPath
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The iteration within which this task will be completed
  - name: Node Name
    reference_name: System.NodeName
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Parent
    reference_name: System.Parent
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Reason
    reference_name: System.Reason
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The reason why the task is in its current state
  - name: Related Link Count
    reference_name: System.RelatedLinkCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Remote Link Count
    reference_name: System.RemoteLinkCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Rev
    reference_name: System.Rev
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Revised Date
    reference_name: System.RevisedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: State
    reference_name: System.State
    type: null
    read_only: false
    required: true
    default_value: New
    help_text: New = New work not yet activated; Active = work remains to be done;
      Closed = tested and checked in.
  - name: Tags
    reference_name: System.Tags
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Team Project
    reference_name: System.TeamProject
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Title
    reference_name: System.Title
    type: null
    read_only: false
    required: true
    default_value: null
    help_text: Work required and how this will implement a User Story
  - name: Watermark
    reference_name: System.Watermark
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Work Item Type
    reference_name: System.WorkItemType
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
