schema_version: '1.0'
generated_at_utc: '2026-02-06T23:14:16.861408+00:00'
source:
  method: extract_json_bootstrap
  input_file: data.json
work_item_type:
  name: Test Case
  reference_name: Microsoft.VSTS.WorkItemTypes.TestCase
  description: Server-side data for a set of steps to be tested.
  is_disabled: false
  states:
  - name: Design
    category: Proposed
    color: b2b2b2
  - name: Ready
    category: InProgress
    color: 007acc
  - name: Closed
    category: Completed
    color: '339933'
  fields:
  - name: Integration Build
    reference_name: Microsoft.VSTS.Build.IntegrationBuild
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The build in which the bug was fixed
  - name: Activated By
    reference_name: Microsoft.VSTS.Common.ActivatedBy
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Activated Date
    reference_name: Microsoft.VSTS.Common.ActivatedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Closed By
    reference_name: Microsoft.VSTS.Common.ClosedBy
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Closed Date
    reference_name: Microsoft.VSTS.Common.ClosedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Priority
    reference_name: Microsoft.VSTS.Common.Priority
    type: null
    read_only: false
    required: false
    default_value: '2'
    help_text: Importance of this test case to the business goals of the product.
      1=Most important.
  - name: State Change Date
    reference_name: Microsoft.VSTS.Common.StateChangeDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Automated Test Id
    reference_name: Microsoft.VSTS.TCM.AutomatedTestId
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The ID of the test that automates this test case
  - name: Automated Test Name
    reference_name: Microsoft.VSTS.TCM.AutomatedTestName
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The name of the test that automates this test case
  - name: Automated Test Storage
    reference_name: Microsoft.VSTS.TCM.AutomatedTestStorage
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The assembly containing the test that automates this test case
  - name: Automated Test Type
    reference_name: Microsoft.VSTS.TCM.AutomatedTestType
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The type of the test that automates this test case
  - name: Automation status
    reference_name: Microsoft.VSTS.TCM.AutomationStatus
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Local Data Source
    reference_name: Microsoft.VSTS.TCM.LocalDataSource
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Parameters
    reference_name: Microsoft.VSTS.TCM.Parameters
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Steps
    reference_name: Microsoft.VSTS.TCM.Steps
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: Steps required to perform the test
  - name: Area ID
    reference_name: System.AreaId
    type: null
    read_only: false
    required: true
    default_value: null
    help_text: null
  - name: Area Level 1
    reference_name: System.AreaLevel1
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 2
    reference_name: System.AreaLevel2
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 3
    reference_name: System.AreaLevel3
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 4
    reference_name: System.AreaLevel4
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 5
    reference_name: System.AreaLevel5
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 6
    reference_name: System.AreaLevel6
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Level 7
    reference_name: System.AreaLevel7
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Area Path
    reference_name: System.AreaPath
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The area of the product with which this test case is associated
  - name: Assigned To
    reference_name: System.AssignedTo
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The person currently working on this test case
  - name: Attached File Count
    reference_name: System.AttachedFileCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Authorized As
    reference_name: System.AuthorizedAs
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Authorized Date
    reference_name: System.AuthorizedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Board Column
    reference_name: System.BoardColumn
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Board Column Done
    reference_name: System.BoardColumnDone
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Board Lane
    reference_name: System.BoardLane
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Changed By
    reference_name: System.ChangedBy
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Changed Date
    reference_name: System.ChangedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Comment Count
    reference_name: System.CommentCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Created By
    reference_name: System.CreatedBy
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Created Date
    reference_name: System.CreatedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Description
    reference_name: System.Description
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: Purpose of this test; requirement tested
  - name: External Link Count
    reference_name: System.ExternalLinkCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: History
    reference_name: System.History
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: Discussion thread plus automatic record of changes
  - name: Hyperlink Count
    reference_name: System.HyperLinkCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: ID
    reference_name: System.Id
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration ID
    reference_name: System.IterationId
    type: null
    read_only: false
    required: true
    default_value: null
    help_text: null
  - name: Iteration Level 1
    reference_name: System.IterationLevel1
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 2
    reference_name: System.IterationLevel2
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 3
    reference_name: System.IterationLevel3
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 4
    reference_name: System.IterationLevel4
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 5
    reference_name: System.IterationLevel5
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 6
    reference_name: System.IterationLevel6
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Level 7
    reference_name: System.IterationLevel7
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Iteration Path
    reference_name: System.IterationPath
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The iteration within which this bug will be fixed
  - name: Node Name
    reference_name: System.NodeName
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Parent
    reference_name: System.Parent
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Reason
    reference_name: System.Reason
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: The reason why the test case is in the current state
  - name: Related Link Count
    reference_name: System.RelatedLinkCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Remote Link Count
    reference_name: System.RemoteLinkCount
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Rev
    reference_name: System.Rev
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Revised Date
    reference_name: System.RevisedDate
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: State
    reference_name: System.State
    type: null
    read_only: false
    required: true
    default_value: Design
    help_text: The workflow state of the test case
  - name: Tags
    reference_name: System.Tags
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Team Project
    reference_name: System.TeamProject
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Title
    reference_name: System.Title
    type: null
    read_only: false
    required: true
    default_value: null
    help_text: Short description of the test case used to differentiate it in a list
      or report
  - name: Watermark
    reference_name: System.Watermark
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
  - name: Work Item Type
    reference_name: System.WorkItemType
    type: null
    read_only: false
    required: false
    default_value: null
    help_text: null
