# LOCAL CLI CONTEXT. SAFE TO EDIT.
# This file stores local operator defaults and may be overwritten by `adoctl context set` or `adoctl home`.
schema_version: '1.0'
org_url: https://some.special.org/PMW
project: White Hot
team: DSA
current_iteration: FY26-Q2-03
